workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Extract and Check ZIP Content
        script: |
          unzip "neoncall-purple-studio (6).zip" -d ./extracted_app
          echo "=== LIST OF ALL FILES AND FOLDERS ==="
          find ./extracted_app -maxdepth 3
          exit 1
    artifacts:
      - "*.apk"
      
      
